# Generated by Django 2.1.7 on 2019-03-14 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('comment_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='评论id')),
                ('nickName', models.CharField(max_length=50, verbose_name='昵称')),
                ('gender', models.IntegerField(verbose_name='性别')),
                ('cityName', models.CharField(max_length=10, verbose_name='所在城市')),
                ('score', models.FloatField(verbose_name='评分')),
                ('content', models.CharField(max_length=500, verbose_name='评论')),
                ('start_time', models.CharField(max_length=30, verbose_name='评论时间')),
            ],
            options={
                'verbose_name': '影评表',
                'verbose_name_plural': '影评表',
                'db_table': 'movie_comments',
            },
        ),
        migrations.CreateModel(
            name='MovieInfoModel',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='电影id')),
                ('name', models.CharField(max_length=50, verbose_name='电影名称')),
                ('enm', models.CharField(max_length=50, verbose_name='电影英文名')),
                ('type', models.CharField(max_length=50, verbose_name='电影类型')),
                ('region', models.CharField(max_length=50, verbose_name='电影地区')),
                ('lang', models.CharField(max_length=20, verbose_name='电影语言')),
                ('score', models.FloatField(verbose_name='电影评分')),
                ('release_time', models.CharField(max_length=30, verbose_name='电影上映时间')),
                ('img', models.CharField(max_length=100, verbose_name='电影海报')),
                ('videourl', models.CharField(max_length=100, verbose_name='电影宣传视频')),
                ('dra', models.CharField(max_length=300, verbose_name='电影简介')),
                ('info', models.CharField(max_length=1000, verbose_name='电影信息')),
            ],
            options={
                'verbose_name': '电影基本信息表',
                'verbose_name_plural': '电影基本信息表',
                'db_table': 'movie_info',
            },
        ),
        migrations.CreateModel(
            name='RequestInfoModel',
            fields=[
                ('movie_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=200, verbose_name='电影名称')),
                ('request_date', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'verbose_name': '请求信息表',
                'verbose_name_plural': '请求信息表',
                'db_table': 'request_info',
            },
        ),
        migrations.AddField(
            model_name='commentsmodel',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.MovieInfoModel'),
        ),
    ]
