# Generated by Django 2.1.7 on 2019-03-14 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieinfomodel',
            name='info',
        ),
    ]
