# Generated by Django 2.0.3 on 2019-03-23 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestinfomodel',
            name='create_date',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='requestinfomodel',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='请求时间'),
        ),
    ]
