# Generated by Django 2.1.7 on 2019-03-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_remove_movieinfomodel_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfomodel',
            name='info',
            field=models.CharField(default=1, max_length=1000, verbose_name='电影信息'),
            preserve_default=False,
        ),
    ]
