# Generated by Django 2.1.7 on 2019-04-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_auto_20190405_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='maoyancommentsmodel',
            name='uuid',
            field=models.CharField(default='', max_length=200, verbose_name='电影uuid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maoyanmovieinfo',
            name='uuid',
            field=models.CharField(default='1', max_length=200, unique=True, verbose_name='电影uuid'),
            preserve_default=False,
        ),
    ]
